spryngsms-enterCode:
    path:       /enterCode
    defaults:   { _controller: 'SimpleSAML\Module\spryngsms\Controller\OTP::enterCode' }
spryngsms-validateCode:
    path:       /validateCode
    defaults:   { _controller: 'SimpleSAML\Module\spryngsms\Controller\OTP::validateCode' }
spryngsms-promptResend:
    path:       /promptResend
    defaults:   { _controller: 'SimpleSAML\Module\spryngsms\Controller\OTP::promptResend' }
spryngsms-sendCode:
    path:       /sendCode
    defaults:   { _controller: 'SimpleSAML\Module\spryngsms\Controller\OTP::sendCode' }

